python train.py \
--dataset colored_mnist \
--method_name irm \
--match_case 0.01 \
--penalty_irm 0.1 \
--epochs 100 \
--batch_size 128 \
--pos_metric cos \
--match_flag 1 \
--test_metric acc \
--img_c 3 --img_w 128 --img_h 128 \
--train_domains R G B \
--test_domains W RGB